[project]
name = "wifi-diagnostic-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "uvicorn>=0.52.4",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.22.3",
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
